### ISSUE TITLE
Fix style issues

### ISSUE THREAD

**Issue by madprime** [abramconnelly/clinvar-report#1]
Mostly minor, but I can see numerous style issues in src/clinvar-report.py when I opened it in my editor, e.g....
- 2-space instead of 4-space indentations (e.g. L525 & later lines)
- duplicate import of sys
- missing space after comma in L19 and L20

Maybe try using a linter? Having an editor set up with linting plug-ins is really nice! The Atom editor has been nice for me to use, I've been using the "linter" plugin and added pylint and flake8.

**Comment by abramconnelly** [comment]
Runing pylint on the updated code produces the following:

```
************* Module src.clinvar_report
R: 55, 4: Too many arguments (6/5) (too-many-arguments)
R: 53, 0: Too few public methods (1/2) (too-few-public-methods)
W: 77, 0: Unused argument 'args' (unused-argument)
R: 75, 0: Too few public methods (1/2) (too-few-public-methods)
R:123, 0: Too few public methods (1/2) (too-few-public-methods)
W:168, 0: Unused argument 'args' (unused-argument)
R:190, 4: Method could be a function (no-self-use)
R:248, 4: Method could be a function (no-self-use)
W:331, 0: Unused argument 'args' (unused-argument)
R:388, 0: Too many local variables (18/15) (too-many-locals)
R:388, 0: Too many branches (23/12) (too-many-branches)
R:388, 0: Too many statements (61/50) (too-many-statements)
R:495, 0: Too many local variables (26/15) (too-many-locals)
W:564, 8: No exception type(s) specified (bare-except)
R:495, 0: Too many branches (17/12) (too-many-branches)
R:495, 0: Too many statements (80/50) (too-many-statements)
```

Indentation, redundant imports and the spacing issues have been resolved.  I've fixed some other styling issues picked up from the linter, both from the code I've added and inherited from the original source.

I'm marking this issue as resolved because the main concerns of this ticket have been addressed.  Another issue can be opened to address the other styling issues if desired.

**Comment by madprime** [comment]
Thanks! :)
